library(qqman)
pdf("Vechur_94_ihs_R.pdf", width = 6, height = 4, bg = "white")
man <- read.table("Vechur_94_ihs_R.txt", header=T)
snps <- c('AX-429218429')
head(man)
as.data.frame(table(man$CHR))
d <- manhattan(man,chr = 'CHR',bp='Bp',p='P',snp='SNP',adjustcolor("grey", alpha.f = 0.2),logp = FALSE,ylab='',xlab='',cex=1.0,cex.lab=1.5,cex.axis=1.0,ylim=c(-5.0,4.5),highlight=snps,xlim = c(0.35,65),font.axis=2,lwd=2)
+axis(1,lwd = 2.0, lab=F)
+axis(2,lwd = 2.0, lab=F)
#abline(h=c(2.0, -2.0), col=c("blue","blue" ), lwd = 1.5)
dev.off()
getwd()
col=c("blue",alpha.f = 0.2)


library(qqman)
pdf("Mng_94_ihs_R.pdf", width = 6, height = 4, bg = "white")
man <- read.table("Mng_94_ihs_R.txt", header=T)
snps <- c('AX-503140053')
head(man)
as.data.frame(table(man$CHR))
d <- manhattan(man,chr = 'CHR',bp='Bp',p='P',snp='SNP',adjustcolor("grey", alpha.f = 0.2),logp = FALSE,ylab='',xlab='',cex=1.0,cex.lab=1.5,cex.axis=1.0,ylim=c(-5.0,4.5),highlight=snps,xlim = c(0.35,65),font.axis=2,lwd=2)
+axis(1,lwd = 2.0, lab=F)
+axis(2,lwd = 2.0, lab=F)
#abline(h=c(2.0, -2.0), col=c("blue","blue" ), lwd = 1.5)
dev.off()
getwd()
col=c("blue",alpha.f = 0.2)


library(qqman)
pdf("Tall_94_ihs_R.pdf", width = 6, height = 4, bg = "white")
man <- read.table("Tall_94_ihs_R.txt", header=T)
snps <- c('AX-503140053','AX-429218429')
head(man)
as.data.frame(table(man$CHR))
d <- manhattan(man,chr = 'CHR',bp='Bp',p='P',snp='SNP',adjustcolor("grey", alpha.f = 0.2),logp = FALSE,ylab='',xlab='',cex=1.0,cex.lab=1.5,cex.axis=1.0,ylim=c(-5.0,5.0),highlight=snps,xlim = c(0.35,70),font.axis=2,lwd=2)
+axis(1,lwd = 2.0, lab=F)
+axis(2,lwd = 2.0, lab=F)
#abline(h=c(2.0, -2.0), col=c("blue","blue" ), lwd = 1.5)
dev.off()
getwd()
col=c("blue",alpha.f = 0.2)

